### ISSUE TITLE
PHPv7 migration

### ISSUE THREAD

**Issue by u07** [splitbrain/dokuwiki-stickbuilder#2]
Hello! Could you please update the PHP in the distro? Version 5 does not support UTF8 on Windows systems, so users have to enable transliteration, which is not so cool.

For my wiki I've taken the new PHPv7 precompiled files from this project: https://usbwebserver.yura.mk.ua MicroApache showed no errors, UTF8 is now in business. working without any noticeable flaws. Just a few plugins like LATEX and OrphanMedia should be patched, like replacing &$handler to Doku_Handler $handler.

**Comment by splitbrain** [comment]
Can you give this a try please?
[dokuwikistick.zip](https://github.com/splitbrain/dokuwiki-stickbuilder/files/4384151/dokuwikistick.zip)

**Comment by u07** [comment]
Checked, Win7x64. No problems so far, except a few plugins, see the image attached. Not a big problem though, just require a polishing: https://github.com/Fweeb/dokuwiki_plugin_html5video/issues/9
![Безымянный 1](https://user-images.githubusercontent.com/20968145/77609948-2efc4c80-6f43-11ea-8adb-4d5fb949b052.jpg)

**Comment by cziehr** [comment]
Hi andi,

I found this issue when searching for a PHP 7-release of DokuWikiStick. I downloaded the archive you provided in the second post, but when I try to start this version of DokuWikiStick, I get the following error (in German):

![dokuwikistick_php7_error](https://user-images.githubusercontent.com/580647/98003909-9a6a9e80-1def-11eb-8ae0-453f1fc6e7d1.png)

After trying it on 3 different computers (all with Windows 10) and it worked on no one, I think something is not ok with the dll. I've the Microsoft Visual C++ Redistributable Packages installed (as you also see on the screenshot), but also on one pc without them, the same error occured.

I'm not sure where to search the error (Google doesn't help much), because I'm not familiar with the Visual C++-stuff. Do you have a hint for me?

Thanks,
Christoph

**Comment by u07** [comment]
@cziehr, I probably know the answer. The lib is UPX-packed - a thing that definitely shouldn't have been done. See here: https://github.com/upx/upx/issues/203 

The lib uses Control Flow Guard, a new piece of security by MS, so after messing with the file, it becomes invalid. Introduced in 8.1, it did not affect Win7, so in my environment it purrs like a kitty. 

Does it work if you remove that lib from /tmp/? There is a valid copy in SysWOW64 which will be used instead.

**Comment by cziehr** [comment]
Thanks for your help, u07!

I removed vcruntime140.dll and the message disappeared. But now there is another problem. In the command-line-window which pops up is displayed:
`mapache.exe: Syntax error on line 18 of C:/Users/Christoph/Downloads/dokuwikistick PHP7/dokuwikistick/server/conf/httpd.conf: Cannot load php/php7apache2_4.dll into server: Falscher Parameter.`

("Falscher Parameter" means "Wrong Parameter")

The content of line 18 is:

`LoadModule php7_module php/php7apache2_4.dll`

The file exists, and I've also tried to set the absolute path instead of the relative, but I got the same error. I don't know what could be wrong with the parameter - if I google the _LoadModule php7_module_-command, always this format is used.

Do you have a hint again for me?

Thanks,
Christoph

**Comment by u07** [comment]
I think, we should ask @splitbrain to unpack the rest of the libraries :) or to remove the cf-guard flag. Though, I don't know, if it affects safety, or not. 

In your case I believe, php7ts.dll should be replaced with the original one from the Internet. Or you can patch it with [PE tools](https://github.com/petoolse/petools/releases). Go to Tools > PE editor, find php7ts.dll, click "Optional header" and change Dll characteristics from 4140 to just 140. CF-guard will be disabled.

**Comment by cziehr** [comment]
Hi u07,

I took php7ts.dll from the archive linked in your first post (https://usbwebserver.yura.mk.ua). Then Microapache started, but showed an additional error with php_opcache.dll. After this, I took all the other php-dll-files also from the other archive, and there were no further errors.

The only error I still encounter is that there seems to be no ssl-support inside DokuWiki. When I try to download any extension with the plugin manager, this doesn't work. But I think this should also be possible to fix.

Thanks for the help so far!

**Comment by splitbrain** [comment]
guys, please use the script in this repo to build new versions. all things you figure out should be reflected in the build script.

**Comment by u07** [comment]
@splitbrain, but it will build PHPv5, won't it?

**Comment by splitbrain** [comment]
use the php7 branch

**Comment by cziehr** [comment]
Hi Andi, if I use your script, I get the same error as described in my first post (#4 of this thread).

**Comment by splitbrain** [comment]
that was to expected. the zip above was made with this script. what you discovered so far needs to be incorporated into the script.

**Comment by u07** [comment]
@cziehr, yes, as we just found a bug, we have to suggest a fix... How about this: run the script with the latest UPX binary from the DEVEL branch. It's September 06: https://github.com/upx/upx-automatic-builds/branches

Latest UPX will not compress/corrupt protected files (there was a patch in august). Should help. I don't have W10 and can't check by myself.

**Comment by splitbrain** [comment]
I updated the branch to something that seems to work on win10 (using the most current stable upx). Using a devel UPX might simplify the whole process a bit. Testing and PRs welcome.

**Comment by cziehr** [comment]
> @cziehr, yes, as we just found a bug, we have to suggest a fix... How about this: run the script with the latest UPX binary from the DEVEL branch. It's September 06: https://github.com/upx/upx-automatic-builds/branches
> 
> Latest UPX will not compress/corrupt protected files (there was a patch in august). Should help. I don't have W10 and can't check by myself.

@u07
I tried with the devel from september, and it worked!


> I updated the branch to something that seems to work on win10 (using the most current stable upx). Using a devel UPX might simplify the whole process a bit. Testing and PRs welcome.

@splitbrain
It seems that we parallel found a working solution. The problem is solved for me!

Thank you for your efforts! Tell me if you have something special to test. I will also test your version now.

**Comment by cziehr** [comment]
@splitbrain 

I did a short test of the basic functions of DokuWiki, compiled with your script and this upx-version: https://github.com/upx/upx-automatic-builds/tree/master-20200122-d7ba31c-tr (the latest master, not devel). It seems that everything works.

I will perform some further test on the weekend and tell you if everything works.

A big thank you again for this awesome software!

**Comment by u07** [comment]
Nice to hear! Can you please publish a new prebuilt archive here for others? Or may be in the "release" section of this repo

**Comment by cziehr** [comment]
I don't know how to put the archive here on github, but I've uploaded a zip on my server. It also added the files of the recent Hogfather-DokuWiki-release. The whole DokuWikiStick is ready to use after unpacking:
https://download.einsatzleiterwiki.de/dokuwiki_on_a_stick_apache_2-4-46_php_7-4-12.zip
I will leave the archive on my server till a php7-version is available at download.dokuwiki.org

I succesfully tested on:
- Windows 10 Enterprise LTSC 1809
- Windows 10 Enterprise 1903
- Windows 10 Pro 1909
- Windows 10 Home 2004

**Comment by Michaelsy** [comment]
> `https://download.einsatzleiterwiki.de/dokuwiki_on_a_stick_apache_2-4-46_php_7-4-12.zip`

Tested with Win7, but only in the basic version, i.e. without additional plugins and templates. 
Result: no abnormalities.

\- Michael Sy.

**Comment by splitbrain** [comment]
download.dokuwiki.org is updated now.
